version: '3'
services:
  web:
      build: .
      command: npm run dev
      volumes:
        - .:/gast0s
        - ./node_modules:/gast0s/node_modules
      ports:
        - "5000:3000"
      environment:
        HOST: 0.0.0.0
